export const API_ERROR_CODES = {
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
    ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
    REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
    CSRF_INVALID: "CSRF_INVALID",

    BAD_REQUEST: "BAD_REQUEST",
    FORBIDDEN: "FORBIDDEN",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    //GATEWAY_TIMEOUT: "GATEWAY_TIMEOUT",

    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

    //RATE_LIMITED: "RATE_LIMITED",
    //TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

    UNKNOWN: "UNKNOWN",
} as const

export type ApiErrorCode = typeof API_ERROR_CODES[keyof typeof API_ERROR_CODES]