export const API_ERROR_CODES = {
    CSRF_INVALID: "CSRF_INVALID",
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
    ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
    REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
    MUST_CHANGE_CREDENTIALS: "MUST_CHANGE_CREDENTIALS",

    BAD_REQUEST: "BAD_REQUEST",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    //PASSWORD_RESET_TOKEN_INVALID: "PASSWORD_RESET_TOKEN_INVALID",
    RATE_LIMITED: "RATE_LIMITED",
    //TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    //GATEWAY_TIMEOUT: "GATEWAY_TIMEOUT",

    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

    UNKNOWN: "UNKNOWN",
} as const

export type ApiErrorCode = typeof API_ERROR_CODES[keyof typeof API_ERROR_CODES]